language: python
python:
  - "3.8"

# install dependencies
install:
  - pip install -r requirements.txt

# run the tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pytest --cov-config=.coveragerc --cov=src

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"