language: python
python:
  - "3.8"

# install dependencies
install: "make"

# run the tests
script:
  - make test

# cache pip dependencies
cache: pip

# upload coverage report to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"