language: python
python:
  - "3.8"

# cache pip dependencies
cache: pip

# addons here
addons:
  sonarcloud:
    organization: "soumithri-sonar-organization"

# install dependencies
install: "make"

# run the tests
script:
  - make test
  - sonar-scanner -Dsonar.verbose=true -X

# upload coverage report to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"